// src/migrations/constants/seeding-data.js

const DEFAULT_LEVELS = [
  { level: 1, name: '新手階' },
  { level: 2, name: '初階' },
  { level: 3, name: '初中階' },
  { level: 4, name: '中階' },
  { level: 5, name: '中進階' },
  { level: 6, name: '高階' },
  { level: 7, name: '職業級' },
];

const DEFAULT_CITIES = [
  { zip_code: '100', city: '臺北市', district: '中正區' },
  { zip_code: '103', city: '臺北市', district: '大同區' },
  { zip_code: '104', city: '臺北市', district: '中山區' },
  { zip_code: '105', city: '臺北市', district: '松山區' },
  { zip_code: '106', city: '臺北市', district: '大安區' },
  { zip_code: '108', city: '臺北市', district: '萬華區' },
  { zip_code: '110', city: '臺北市', district: '信義區' },
  { zip_code: '111', city: '臺北市', district: '士林區' },
  { zip_code: '112', city: '臺北市', district: '北投區' },
  { zip_code: '114', city: '臺北市', district: '內湖區' },
  { zip_code: '115', city: '臺北市', district: '南港區' },
  { zip_code: '116', city: '臺北市', district: '文山區' },
  { zip_code: '200', city: '基隆市', district: '仁愛區' },
  { zip_code: '201', city: '基隆市', district: '信義區' },
  { zip_code: '202', city: '基隆市', district: '中正區' },
  { zip_code: '203', city: '基隆市', district: '中山區' },
  { zip_code: '204', city: '基隆市', district: '安樂區' },
  { zip_code: '205', city: '基隆市', district: '暖暖區' },
  { zip_code: '206', city: '基隆市', district: '七堵區' },
  { zip_code: '207', city: '新北市', district: '萬里區' },
  { zip_code: '208', city: '新北市', district: '金山區' },
  { zip_code: '220', city: '新北市', district: '板橋區' },
  { zip_code: '221', city: '新北市', district: '汐止區' },
  { zip_code: '222', city: '新北市', district: '深坑區' },
  { zip_code: '223', city: '新北市', district: '石碇區' },
  { zip_code: '224', city: '新北市', district: '瑞芳區' },
  { zip_code: '226', city: '新北市', district: '平溪區' },
  { zip_code: '227', city: '新北市', district: '雙溪區' },
  { zip_code: '228', city: '新北市', district: '貢寮區' },
  { zip_code: '231', city: '新北市', district: '新店區' },
  { zip_code: '232', city: '新北市', district: '坪林區' },
  { zip_code: '233', city: '新北市', district: '烏來區' },
  { zip_code: '234', city: '新北市', district: '永和區' },
  { zip_code: '235', city: '新北市', district: '中和區' },
  { zip_code: '236', city: '新北市', district: '土城區' },
  { zip_code: '237', city: '新北市', district: '三峽區' },
  { zip_code: '238', city: '新北市', district: '樹林區' },
  { zip_code: '239', city: '新北市', district: '鶯歌區' },
  { zip_code: '241', city: '新北市', district: '三重區' },
  { zip_code: '242', city: '新北市', district: '新莊區' },
  { zip_code: '243', city: '新北市', district: '泰山區' },
  { zip_code: '244', city: '新北市', district: '林口區' },
  { zip_code: '247', city: '新北市', district: '蘆洲區' },
  { zip_code: '248', city: '新北市', district: '五股區' },
  { zip_code: '249', city: '新北市', district: '八里區' },
  { zip_code: '251', city: '新北市', district: '淡水區' },
  { zip_code: '252', city: '新北市', district: '三芝區' },
  { zip_code: '253', city: '新北市', district: '石門區' },
  { zip_code: '260', city: '宜蘭縣', district: '宜蘭市' },
  { zip_code: '263', city: '宜蘭縣', district: '壯圍鄉' },
  { zip_code: '261', city: '宜蘭縣', district: '頭城鎮' },
  { zip_code: '262', city: '宜蘭縣', district: '礁溪鄉' },
  { zip_code: '264', city: '宜蘭縣', district: '員山鄉' },
  { zip_code: '265', city: '宜蘭縣', district: '羅東鎮' },
  { zip_code: '266', city: '宜蘭縣', district: '三星鄉' },
  { zip_code: '267', city: '宜蘭縣', district: '大同鄉' },
  { zip_code: '268', city: '宜蘭縣', district: '五結鄉' },
  { zip_code: '269', city: '宜蘭縣', district: '冬山鄉' },
  { zip_code: '270', city: '宜蘭縣', district: '蘇澳鎮' },
  { zip_code: '272', city: '宜蘭縣', district: '南澳鄉' },
  { zip_code: '290', city: '宜蘭縣', district: '釣魚臺' },
  { zip_code: '209', city: '連江縣', district: '南竿鄉' },
  { zip_code: '210', city: '連江縣', district: '北竿鄉' },
  { zip_code: '211', city: '連江縣', district: '莒光鄉' },
  { zip_code: '212', city: '連江縣', district: '東引鄉' },
  { zip_code: '300東區', city: '新竹市', district: '東區' },
  { zip_code: '300北區', city: '新竹市', district: '北區' },
  { zip_code: '300香山區', city: '新竹市', district: '香山區' },
  { zip_code: '308', city: '新竹縣', district: '寶山鄉' },
  // ... 其他城市資料 (這裡只顯示部分，實際使用時請包含完整資料)
];

const DEFAULT_FACILITIES = [
  { name: '冷氣' },
  { name: '飲水機' },
  { name: '廁所' },
  { name: '吹風機' },
  { name: '淋浴間' },
  { name: '羽球用品販賣' },
  { name: '穿線機' },
  { name: '停車場' },
];

const DEFAULT_ACTIVITIES = [
  {
    name: '歡樂團',
    organizer: '小明羽球社',
    start_time: new Date('2025-03-22T09:00:00Z'),
    end_time: new Date('2025-03-22T12:00:00Z'),
    venue_name: '中壢三芝小鹿羽球館',
    zip_code: 320,
    address: '三芝路280號',
    ball_type: '黑摩亞/No.1',
    participant_count: 24,
    booked_count: 5,
    rental_lot: 3,
    brief: '6人開團',
    contact_name: '阿不拉',
    contact_phone: '0911582136',
    contact_line: '0911582136',
    points: 200,
    status: 'published',
  },
  {
    name: '晨練羽球會',
    organizer: '小美羽球社',
    start_time: new Date('2025-03-23T06:30:00Z'),
    end_time: new Date('2025-03-23T08:30:00Z'),
    venue_name: '桃園市立體育館',
    zip_code: 330,
    address: '中正路100號',
    ball_type: 'RSL No.5',
    participant_count: 20,
    booked_count: 8,
    rental_lot: 2,
    brief: '早起打球精神好',
    contact_name: '小楊',
    contact_phone: '0923123456',
    contact_line: 'xiaoyang',
    points: 150,
    status: 'published',
  },
  {
    name: '週末大亂鬥',
    organizer: '阿明羽球社',
    start_time: new Date('2025-03-29T14:00:00Z'),
    end_time: new Date('2025-03-29T17:00:00Z'),
    venue_name: '台北南港羽球館',
    zip_code: 115,
    address: '南港路三段50號',
    ball_type: '威克多金黃2號',
    participant_count: 30,
    booked_count: 10,
    rental_lot: 4,
    brief: '高手過招，快來挑戰',
    contact_name: '老王',
    contact_phone: '0988777666',
    contact_line: 'laowang88',
    points: 300,
    status: 'published',
  },
  {
    name: '輕鬆下午打',
    organizer: '小志同好會',
    start_time: new Date('2025-04-01T13:00:00Z'),
    end_time: new Date('2025-04-01T15:00:00Z'),
    venue_name: '林口體育館',
    zip_code: 244,
    address: '文化一路二段188號',
    ball_type: '勝利Master Ace',
    participant_count: 16,
    booked_count: 6,
    rental_lot: 2,
    brief: '適合初學者',
    contact_name: '小美',
    contact_phone: '0977123456',
    contact_line: 'meimei',
    points: 120,
    status: 'published',
  },
  {
    name: '夜貓子羽球團',
    organizer: '不睡覺俱樂部',
    start_time: new Date('2025-04-05T21:00:00Z'),
    end_time: new Date('2025-04-05T23:30:00Z'),
    venue_name: '台中大都會羽球中心',
    zip_code: 407,
    address: '台灣大道四段999號',
    ball_type: 'Yonex AS-30',
    participant_count: 20,
    booked_count: 12,
    rental_lot: 3,
    brief: '夜深人靜來開打',
    contact_name: '阿明',
    contact_phone: '0933123123',
    contact_line: 'aming',
    points: 180,
    status: 'published',
  },
  {
    name: '新手教學團',
    organizer: '羽球新手村',
    start_time: new Date('2025-04-10T10:00:00Z'),
    end_time: new Date('2025-04-10T12:00:00Z'),
    venue_name: '新竹縣立羽球館',
    zip_code: 302,
    address: '中山路88號',
    ball_type: 'No.1',
    participant_count: 12,
    booked_count: 4,
    rental_lot: 2,
    brief: '教學導向活動',
    contact_name: '阿志',
    contact_phone: '0955111222',
    contact_line: 'azhi88',
    points: 100,
    status: 'published',
  },
  {
    name: '假日親子場',
    organizer: '親子羽球樂園',
    start_time: new Date('2025-04-13T15:00:00Z'),
    end_time: new Date('2025-04-13T17:00:00Z'),
    venue_name: '永和羽球館',
    zip_code: 234,
    address: '永和路一段20號',
    ball_type: '勝利No.1',
    participant_count: 18,
    booked_count: 7,
    rental_lot: 3,
    brief: '歡迎親子參加',
    contact_name: '小芳',
    contact_phone: '0966333444',
    contact_line: 'xiaofang',
    points: 140,
    status: 'published',
  },
  {
    name: '學生特惠團',
    organizer: '師大羽球社',
    start_time: new Date('2025-04-15T18:00:00Z'),
    end_time: new Date('2025-04-15T20:00:00Z'),
    venue_name: '師大體育館',
    zip_code: 106,
    address: '和平東路一段1號',
    ball_type: '羽球博士1號',
    participant_count: 25,
    booked_count: 14,
    rental_lot: 4,
    brief: '學生憑證報名享折扣',
    contact_name: '小正',
    contact_phone: '0944555666',
    contact_line: 'zheng',
    points: 160,
    status: 'published',
  },
  {
    name: '女子限定羽球團',
    organizer: '女子羽球聯盟',
    start_time: new Date('2025-04-20T09:00:00Z'),
    end_time: new Date('2025-04-20T11:00:00Z'),
    venue_name: '士林運動中心',
    zip_code: 111,
    address: '福港街45號',
    ball_type: 'RSL Classic Tourney',
    participant_count: 15,
    booked_count: 5,
    rental_lot: 2,
    brief: '女生限定活動',
    contact_name: '小芸',
    contact_phone: '0911888999',
    contact_line: 'xiao_yun',
    points: 130,
    status: 'published',
  },
  {
    name: '中午快打團',
    organizer: '午休羽球社',
    start_time: new Date('2025-04-22T12:00:00Z'),
    end_time: new Date('2025-04-22T13:30:00Z'),
    venue_name: '新店羽球會館',
    zip_code: 231,
    address: '北新路三段500號',
    ball_type: '勝利1號',
    participant_count: 10,
    booked_count: 6,
    rental_lot: 2,
    brief: '午休運動組',
    contact_name: '阿宏',
    contact_phone: '0933444555',
    contact_line: 'ahong',
    points: 110,
    status: 'published',
  },
];

const DEFAULT_POINTS_PLAN = [
  { points: 100, value: 100 },
  { points: 300, value: 300 },
  { points: 500, value: 500 },
];

module.exports = {
  DEFAULT_LEVELS,
  DEFAULT_CITIES,
  DEFAULT_FACILITIES,
  DEFAULT_ACTIVITIES,
  DEFAULT_POINTS_PLAN,
};
